-- Problem: The PADS
-- Link: https://www.hackerrank.com/challenges/ThePADS/problem

SELECT CONCAT(NAME,'(',UPPER(SUBSTR(OCCUPATION,1,1)),')') FROM OCCUPATIONS ORDER BY NAME ASC;

SELECT CONCAT('There are a total of ',COUNT(OCCUPATION),' ',LOWER(OCCUPATION),'s.') from OCCUPATIONS GROUP BY OCCUPATION ORDER BY COUNT(OCCUPATION) ASC;
